title: Cruisin Co - Awesome Electric Vehicles
description: Cruisin Co is about state of the art electric vehicles. We have the Cruisin Brain, a fully featured, drive by wire computer. The Cruisin OLED to bring vital statistics to the driver and of course our awesome electric cars.

google_analytics: [Your Google Analytics tracking ID]